openapi: 3.0.0
info:
    version: 1.0.0
    title: Sample API
paths:
    /users/{id}:
        get:
            summary: Gets a user by ID.
            operationId: getUserById
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
            required:
                - id
                - name
